// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapitalChedidApi.Models;

public partial class QuotationsGridColumns
{
    public int ID { get; set; }

    public string DBName { get; set; }

    public string DisplayName { get; set; }

    public int DataType { get; set; }

    public string RelatedTable { get; set; }

    public bool IsSearchable { get; set; }

    public bool IsSortable { get; set; }

    public int? Sorting { get; set; }
}