// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapitalChedidApi.Models;

public partial class QuotationStatus
{
    public int ID { get; set; }

    public string Name { get; set; }

    public string FontColor { get; set; }

    public int? Sorting { get; set; }

    public virtual ICollection<Quotations> Quotations { get; set; } = new List<Quotations>();
}