// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapitalChedidApi.Models;

public partial class Quotations
{
    public int ID { get; set; }

    public string QuotationNo { get; set; }

    public string PolicyOwner { get; set; }

    public string CarMake { get; set; }

    public int? YearOfMake { get; set; }

    public int? Staus { get; set; }

    public DateTime CreationDate { get; set; }

    public virtual QuotationStatus StausNavigation { get; set; }
}