// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapitalChedidApi.Models;

public partial class StaticLists
{
    public int ID { get; set; }

    public string ListName { get; set; }

    public string Description { get; set; }

    public int Value { get; set; }
}