// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CapitalChedidApi.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CapitalChedidApi.Models
{
    public partial class TestAppContext
    {
        private ITestAppContextProcedures _procedures;

        public virtual ITestAppContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TestAppContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITestAppContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class TestAppContextProcedures : ITestAppContextProcedures
    {
        private readonly TestAppContext _context;

        public TestAppContextProcedures(TestAppContext context)
        {
            _context = context;
        }
    }
}
