// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CapitalChedidApi.Models;

public partial class TestAppContext : DbContext
{
    public TestAppContext(DbContextOptions<TestAppContext> options)
        : base(options)
    {
    }

    public virtual DbSet<QuotationStatus> QuotationStatus { get; set; }

    public virtual DbSet<Quotations> Quotations { get; set; }

    public virtual DbSet<QuotationsGridColumns> QuotationsGridColumns { get; set; }

    public virtual DbSet<StaticLists> StaticLists { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<QuotationStatus>(entity =>
        {
            entity.Property(e => e.FontColor).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(250);
        });

        modelBuilder.Entity<Quotations>(entity =>
        {
            entity.Property(e => e.CarMake).HasMaxLength(500);
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PolicyOwner).HasMaxLength(500);
            entity.Property(e => e.QuotationNo).HasMaxLength(50);

            entity.HasOne(d => d.StausNavigation).WithMany(p => p.Quotations)
                .HasForeignKey(d => d.Staus)
                .HasConstraintName("FK_Quotations_QuotationStatus");
        });

        modelBuilder.Entity<QuotationsGridColumns>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_QuotationsSearchColumns");

            entity.Property(e => e.DBName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.RelatedTable).HasMaxLength(50);
        });

        modelBuilder.Entity<StaticLists>(entity =>
        {
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.ListName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}